apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vatcal-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: vatcal
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
